mod error_serialize;
mod files;
mod files_ops;
mod vault_stats;
mod tree;
mod watcher;
mod merge;
mod indexer;
mod link_graph;
mod local_graph;
mod global_graph;
pub mod tag_index;
mod hash_verify;
mod bookmarks;
mod snippets;
